name: Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to cPanel
        run: |
          lftp -u ${{ secrets.DAI_FTP_USERNAME }},${{ secrets.DAI_FTP_PASSWORD }} ${{ secrets.DAI_FTP_SERVER }} <<EOF
          set ssl:verify-certificate no
          set ftp:ssl-allow yes
          set ftp:passive-mode on
          rm -rf *
          mirror -R dist/ .
          bye
          EOF
