name: Publish website to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install lftp -y

      - name: Deploy clean build to cPanel
        run: |
          lftp -c "
          set ssl:verify-certificate no;
          set ftp:ssl-allow yes;
          set ftp:passive-mode on;
          open -u ${{ secrets.DAI_FTP_USERNAME }},${{ secrets.DAI_FTP_PASSWORD }} ${{ secrets.DAI_FTP_SERVER }};
          
          cd 3dai;

          # DELETE everything in target folder
          rm -rf *;

          # upload fresh build
          mirror -R dist/ . --verbose;

          bye
          "
